apiVersion: v1
kind: Template
labels:
  template: jenkins-clojure-agent-template
metadata:
  annotations:
    description: Create a Clojure-capable Jenkins agent
    iconClass: icon-jenkins
    tags: jenkins
  name: jenkins-clojure-agent-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-directory: /home/jenkins
      slave-label: clojure
    labels:
      template: jenkins-clojure-agent-template
      role: jenkins-slave
    name: jenkins-clojure-agent
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds a Clojure-capable Jenkins agent
    labels:
      template: jenkins-clojure-agent-template
    name: jenkins-clojure-agent
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-clojure-agent:latest
    resources: {}
    source:
      type: Git
      contextDir: jenkins/clojure-agent
      git:
        uri: https://github.com/futurice/openshift-templates
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
